export const FIREBASE_ITEMS_GET = "FIREBASE_ITEMS_GET";
export const FIREBASE_ITEMS_DELETE = "FIREBASE_ITEMS_DELETE";
export const FIREBASE_ITEMS_START = "FIREBASE_ITEMS_START";
export const FIREBASE_ITEMS_ERROR = "FIREBASE_ITEMS_ERROR";
